### ISSUE TITLE
duuuuu frickler

### ISSUE THREAD

**Issue by minad** [thelightwasbrighter/raytracer#1]

**Comment by thelightwasbrighter** [comment]
duuhuhuuuhuuuu

**Comment by minad** [comment]
was  geht? Ist der raytracer dein werk? Hab ich dir schonmal meinen gezeigt?

**Comment by thelightwasbrighter** [comment]
Ich hab deinen mal in einem frühen stadium gesehen... den hier hab ich gemacht, ist aber noch in arbeit
